"""Adversarial mutation harness for `eda/`.

Each entry breaks one invariant and names the test that must go red. The repo's
standing rule is that a green suite is not evidence a check can fail
(docs/pipelines/05); this is how that evidence is produced for the EDA package.

    V=/data/project/private/dacon-venvs/dacon311/bin/python
    $V scripts/mutate_eda.py $V        # exit 1 if any mutant survives

⚠️ **A mutant that dies against an already-red test is not a kill.** Run the
suite green first -- `$V -m pytest tests/test_eda.py -o addopts=""` -- or a
broken test will be scored as a passing guard. That happened once and cost two
rounds to notice.

⚠️ It edits files in place and restores them in a `finally`. Do not run it
against a dirty working tree you care about, and do not run it concurrently with
anything else that reads those files.
"""
import pathlib, subprocess, sys

MUTANTS = [
    ("eda/extract/__init__.py",
     "        got, want = set(out), set(self.columns)\n        if got != want:",
     "        got, want = set(out), set(self.columns)\n        if False:",
     "declared-columns check", "test_an_extractor_that_emits_an_undeclared_column_raises"),
    ("eda/extract/__init__.py",
     "        if len(params) != self.arity:",
     "        if False:",
     "arity check", "test_registration_refuses_an_extractor_with_the_wrong_arity"),
    ("eda/gates.py",
     "_ORDER = {FAIL: 0, NA: 1, PASS: 2}",
     "_ORDER = {NA: 0, FAIL: 1, PASS: 2}",
     "fail > na > pass ordering", "test_fail_beats_na_beats_pass"),
    ("eda/analyze/shortcut.py",
     "    return pd.to_numeric(out, errors=\"coerce\")",
     "    return pd.to_numeric(out, errors=\"coerce\").fillna(0)",
     "null labels coerced to 0", "test_head_labels_are_null_where_the_metric_ignores_them"),
    ("eda/driver.py",
     "            if not part.with_suffix(\".DONE\").exists():",
     "            if False:",
     "DONE-marker check in consolidate", "test_consolidate_refuses_a_part_whose_done_marker_is_missing"),
    ("eda/driver.py",
     "        if source.excludes_path(p.relative_to(root).as_posix()):\n            continue",
     "        if False:\n            continue",
     "exclusion in enumerate_source", "test_enumeration_honours_an_exclusion"),
    ("eda/analyze/duplicates.py",
     "    return have[counts > 1].sort_values([\"sha256\", \"file_id\"]).reset_index(drop=True)",
     "    return have.head(0)",
     "duplicate detection", "test_the_duplicate_sweep_finds_cross_source_byte_identity"),
    ("eda/ids.py",
     "        if any(parts[i:i + n] == want for i in range(len(parts) - n + 1)):",
     "        if any(p.startswith(prefix) for p in ['/'.join(parts)]):",
     "component-wise exclusion matching", "test_exclusion_matches_path_components_not_substrings"),
    ("eda/ids.py",
     "    if not isinstance(source_name, str):",
     "    if False:",
     "file_id source-name type guard", "test_file_id_refuses_a_non_string_source"),
    ("eda/gates.py",
     "    missing = [k for k in SUMMARY_KEYS if k not in dupes]",
     "    missing = []",
     "duplicate-summary completeness check", "test_an_incomplete_duplicate_summary_reads_na_not_pass"),
    ("eda/driver.py",
     "            missing = [c for c in FIXED_COLUMNS if c not in frame.columns]",
     "            missing = []",
     "FIXED_COLUMNS check in consolidate", "test_consolidate_refuses_a_part_missing_the_fixed_columns"),
    ("eda/config.py",
     "            if self.pool is not None:",
     "            if False:",
     "whole_file must have pool = null", "test_a_component_source_and_a_whole_file_source_carry_opposite_keys"),
    ("eda/config.py",
     "            if self.cell is not None:",
     "            if False:",
     "component must have cell = null", "test_a_component_source_and_a_whole_file_source_carry_opposite_keys"),
    ("eda/config.py",
     "            if self.cell in UNSCRAPEABLE_CELLS:",
     "            if False:",
     "cells 6/7 cannot be whole_file", "test_cells_6_and_7_cannot_be_whole_file_sources"),
    ("eda/analyze/shortcut.py",
     "        out = out.mask(cells.notna(), cells.map(by_cell))",
     "        pass",
     "head_labels reads CELL_TABLE", "test_head_labels_read_the_cell_table_for_whole_file_rows"),
    ("eda/config.py",
     "        return self.pool if self.row_kind == \"component\" else f\"cell{self.cell}\"",
     "        return self.pool",
     "whole_file partitions by cell", "test_a_whole_file_source_probes_into_its_own_partition"),
    ("configs/eda.yaml",
     "  - name: sonics\n    row_kind: whole_file\n    cell: 8",
     "  - name: sonics\n    pool: D",
     "sonics registered as cell 8, not pool D", "test_the_shipped_config_registers_sonics_as_cell_8_not_pool_d"),
    ("eda/analyze/shortcut.py",
     "HEADS = {c.removeprefix(\"label_\"): i for i, c in enumerate(_LABEL_COLUMNS)}",
     "HEADS = {\"voice_present\": 0, \"music_present\": 1, \"music_fake\": 2, \"voice_fake\": 3}",
     "HEADS derived from manifest order", "test_heads_follow_the_manifest_label_order"),
    ("eda/analyze/shortcut.py",
     "        x, names = build_design(sub, top_k=cfg.top_k, features=features)",
     "        x, names = build_design(sub, top_k=20, features=features)",
     "top_k reaches the audit", "test_analysis_knobs_reach_the_analyses"),
    ("eda/config.py",
     "    if not raw:",
     "    if False:",
     "empty-sources refusal", "test_a_config_with_no_sources_is_refused"),
    ("eda/cli.py",
     "    (out / DUPLICATE_SUMMARY).write_text(",
     "    _unused = (lambda *a, **k: None)(",
     "duplicate summary written unconditionally", "test_the_cli_records_a_clean_sweep"),
    ("eda/analyze/duplicates.py",
     "    if \"sha256\" not in files.columns:",
     "    if False:",
     "NoHashes guard", "test_a_probe_without_hashes_leaves_the_duplicate_gate_na"),
    ("eda/driver.py",
     "    df.attrs[\"missing_partitions\"] = missing",
     "    df.attrs[\"missing_partitions\"] = []",
     "missing-partition reporting", "test_a_partition_with_no_table_is_reported_not_skipped"),
    ("eda/analyze/shortcut.py",
     "        n_splits = max(2, min(cfg.n_splits, minority))",
     "        n_splits = cfg.n_splits",
     "cv clamp to the minority class", "test_the_cross_validation_is_clamped_to_the_minority_class_and_says_so"),
    ("eda/driver.py",
     "from eda.extract import identity as _identity        # noqa: F401",
     "",
     "identity registration side-effect import", "test_importing_the_driver_populates_the_metadata_registry"),
    ("eda/gates.py",
     "    if key == \"relpath\":\n        return values.astype(str).str.strip()",
     "    if False:\n        return values.astype(str).str.strip()",
     "relpath allowlist key", "test_the_allowlist_keys_match_the_shipped_csv_shapes"),
    ("eda/gates.py",
     "            if source.allowlist_column not in (reader.fieldnames or []):",
     "            if False:",
     "misnamed allowlist column -> na", "test_a_misnamed_allowlist_column_is_na_not_fail"),
    ("configs/eda.yaml",
     "    allowlist_key: relpath",
     "    allowlist_key: stem",
     "jamendo allowlist key in the shipped config", "test_the_shipped_config_names_the_real_allowlist_columns"),
    ("eda/driver.py",
     "    if source.blocked:",
     "    if False:",
     "blocked source raises", "test_a_blocked_source_raises_rather_than_enumerating"),
    ("configs/eda.yaml",
     "    blocked: >-",
     "    unread_key: >-",
     "ctrsvdd blocked in the shipped config", "test_the_shipped_config_blocks_ctrsvdd_with_a_reason"),
    ("eda/driver.py",
     "    if not out:",
     "    if False:",
     "empty enumeration raises", "test_a_source_that_yields_no_files_raises_rather_than_returning_empty"),
    ("eda/config.py",
     "        return (self.root if spec.stage == \"interim\" else self.raw) / spec.root",
     "        return self.root / spec.root",
     "raw-stage source root", "test_a_raw_stage_source_reads_from_the_sync_tree"),
    ("configs/eda.yaml",
     "    stage: raw\n    root: mlaad/v9/payload",
     "    root: mlaad/v9",
     "mlaad stage in the shipped config", "test_the_shipped_config_reads_mlaad_from_raw"),
    ("eda/cli.py",
     "        except FileNotFoundError:\n            absent.append(source.name)\n            continue",
     "        except FileNotFoundError:\n            raise",
     "absent source is skipped, not fatal", "test_probe_tolerates_absent_and_blocked_sources_but_not_empty_ones"),
    ("eda/cli.py",
     "    if not probed:",
     "    if False:",
     "nothing probed is a failure", "test_probe_tolerates_absent_and_blocked_sources_but_not_empty_ones"),
    ("eda/driver.py",
     "        raise BlockedSource(f\"source {source.name!r} is blocked: {source.blocked}\")",
     "        raise FileNotFoundError(f\"source {source.name!r} is blocked\")",
     "blocked is distinct from absent", "test_probe_tolerates_absent_and_blocked_sources_but_not_empty_ones"),
    ("eda/gates.py",
     "        if sub.empty:",
     "        if False:",
     "empty allowlist check is na", "test_an_allowlist_over_zero_rows_is_na_not_a_vacuous_pass"),

    # ---------------------------------------------------------------- S tier
    # These live in tests/test_eda_signal.py, so they carry the file with them.
    ("eda/planes.py",
     "    if declared is not None and int(declared) != rate:",
     "    if False:",
     "native rate cross-check",
     "tests/test_eda_signal.py::test_a_declared_rate_that_disagrees_with_the_file_is_refused"),
    ("eda/planes.py",
     "    resampled = resample_poly_to(wav, rate, chain_sr)",
     "    resampled = wav[:, ::max(1, rate // chain_sr)]",
     "chain plane uses the training resampler",
     "tests/test_eda_signal.py::test_the_chain_plane_is_identical_to_what_the_training_path_produces"),
    ("eda/planes.py",
     "    mono = prepare_waveform(torch.from_numpy(resampled)[None], audio)[0]",
     "    mono = torch.from_numpy(resampled).mean(dim=0)",
     "chain plane uses the model's channel policy",
     "tests/test_eda_signal.py::test_the_channel_policy_comes_from_the_config_not_from_a_local_downmix"),
    ("eda/extract/__init__.py",
     '            suffixed = {f"{k}_{plane_name}": v for k, v in out.items()}',
     "            suffixed = dict(out)",
     "signal columns suffixed per plane",
     "tests/test_eda_signal.py::test_every_signal_column_is_emitted_once_per_plane"),
    ("eda/extract/level.py",
     "    return DB_FLOOR if x <= 0 else max(DB_FLOOR, float(20.0 * np.log10(x)))",
     "    return float(20.0 * np.log10(x)) if x > 0 else float('-inf')",
     "dBFS floor instead of -inf",
     "tests/test_eda_signal.py::test_silence_reports_the_floor_and_not_negative_infinity"),
    ("eda/extract/timing.py",
     "    loud = db > SILENCE_DBFS",
     "    loud = db > db.max() + SILENCE_DBFS",
     "silence threshold is absolute",
     "tests/test_eda_signal.py::test_the_silence_threshold_is_absolute_not_relative"),
    ("eda/extract/spectral.py",
     "    flatness = float(np.exp(np.mean(np.log(np.maximum(psd, floor)))) / np.mean(psd))",
     "    _pos = psd[psd > 0]\n    flatness = float(np.exp(np.mean(np.log(_pos))) / np.mean(psd)) if _pos.size == psd.size else 0.0",
     "zero PSD bins floored, not dropped",
     "tests/test_eda_signal.py::test_zero_bins_are_floored_so_flatness_is_computed_not_abandoned"),
    ("eda/extract/spectral.py",
     '        row[f"band_energy_{i}"] = _band(lo, hi, closed=(i == top)) / total',
     '        row[f"band_energy_{i}"] = _band(lo, hi) / total',
     "top band includes the Nyquist bin",
     "tests/test_eda_signal.py::test_band_energies_are_fractions_that_sum_to_one_at_16k"),
    ("eda/extract/spectral.py",
     '        "hf_ratio_8k": _band(CHAIN_NYQUIST_HZ, nyquist, closed=True) / total,',
     '        "hf_ratio_8k": near / total,',
     "hf_ratio_8k is an absolute band",
     "tests/test_eda_signal.py::test_bandwidth_finds_a_low_pass_edge"),
    ('eda/sample.py',
     '    ordered = files.sort_values("file_id", kind="mergesort")',
     '    ordered = files',
     'the draw is sorted before the RNG',
     'tests/test_eda_signal.py::test_the_same_seed_draws_the_same_files_whatever_the_row_order'),
    ('eda/sample.py',
     '    if path.exists() and not force:',
     '    if False:',
     'a recorded draw is not silently replaced',
     'tests/test_eda_signal.py::test_a_recorded_draw_is_not_silently_replaced'),
    ('eda/sample.py',
     '    missing = [i for i in sample.file_ids if i not in have.index]',
     '    missing = []',
     'a draw whose files have gone is refused',
     'tests/test_eda_signal.py::test_a_draw_whose_files_have_gone_is_refused'),
    ('eda/driver.py',
     '    if sample is None:',
     '    if False:',
     'the signal pass will not improvise a sample',
     'tests/test_eda_signal.py::test_the_signal_pass_refuses_to_improvise_a_sample'),
    ('eda/driver.py',
     '    except Exception as exc:                         # noqa: BLE001 -- a row, not a raise\n        # 🔴 The vectors still get a row',
     '    except Exception as exc:                         # noqa: BLE001 -- a row, not a raise\n        raise\n        # 🔴 The vectors still get a row',
     'a decode failure is a row, not a lost census',
     'tests/test_eda_signal.py::test_a_file_that_cannot_be_decoded_is_a_row_not_a_lost_census'),
    ('eda/driver.py',
     '                if wrote != cfg.sample.shard_size:',
     '                if False:',
     'shard size recorded and checked',
     'tests/test_eda_signal.py::test_changing_the_shard_size_between_runs_is_refused'),
    ('eda/driver.py',
     '    dupes = merged["file_id"].duplicated()',
     '    dupes = merged["file_id"].duplicated() & False',
     'signal parts cannot merge with duplicates',
     'tests/test_eda_signal.py::test_signal_parts_that_disagree_cannot_merge_into_a_table'),
    ('eda/driver.py',
     '        if not source.selects_name(p.name):\n            continue',
     '        if False:\n            continue',
     'name_glob selects half a directory',
     'tests/test_eda.py::test_a_source_can_claim_half_a_directory_by_filename'),
    ('eda/config.py',
     '        if self.name_glob and not self.name_glob_reason:',
     '        if False:',
     'a filename glob must say why',
     'tests/test_eda.py::test_a_filename_glob_must_say_why'),
    # --- docs/EDA/09 step 7: the content tier -------------------------------
    ('eda/extract/content.py',
     '    if mono.size < CHUNK:',
     '    if False:',
     'a file too short to measure is a failure',
     'tests/test_eda_content.py::test_a_file_too_short_to_measure_is_a_failure_not_a_zero_ratio'),
    ('eda/extract/content.py',
     'THRESHOLDS = (0.5, 0.4)',
     'THRESHOLDS = (0.5,)',
     'both VAD thresholds are emitted',
     'tests/test_eda_content.py::test_both_thresholds_are_emitted'),
    ('eda/extract/content.py',
     'MIN_SPAN_CHUNKS = 4',
     'MIN_SPAN_CHUNKS = 1',
     'a lone chunk is not a span',
     'tests/test_eda_content.py::test_a_lone_chunk_over_threshold_is_not_a_span'),
    ('models/vendor/silero_vad/__init__.py',
     '        if digest != MODEL_SHA256:',
     '        if False:',
     'the vendored model is digest-checked',
     'tests/test_eda_content.py::test_the_vendored_model_is_verified_against_its_digest'),
    ('models/vendor/silero_vad/__init__.py',
     '    if sample_rate != SAMPLE_RATE:\n        raise ValueError(',
     '    if False:\n        raise ValueError(',
     'the VAD refuses a rate it was not vendored for',
     'tests/test_eda_content.py::test_the_vad_refuses_a_rate_it_was_not_vendored_for'),
    ('eda/driver.py',
     'from eda.extract import content as _content          # noqa: F401',
     '',
     'the driver registers the content tier',
     'tests/test_eda_content.py::test_importing_the_driver_populates_the_content_registry'),
    ('eda/driver.py',
     '                 **flags, **_failed_content()}, arrays)',
     '                 **flags}, arrays)',
     'a decode failure emits the content columns',
     'tests/test_eda_content.py::test_a_decode_failure_emits_every_content_column_unsuffixed'),
    # --- docs/EDA/09 step 6: reading the S tier -----------------------------
    ('eda/analyze/signal.py',
     '                    for group in SIGNAL_SCALARS.values() for c in group\n                    if c not in CHAIN_EXCLUDED)',
     '                    for group in SIGNAL_SCALARS.values() for c in group)',
     'the chain spec drops the published rate',
     'tests/test_eda_report.py::test_the_chain_feature_spec_excludes_the_published_rate_in_disguise'),
    ('eda/analyze/signal.py',
     '    out = out.dropna(subset=[NATIVE, CHAIN])',
     '    out = out',
     'an unpaired row is dropped and counted',
     'tests/test_eda_report.py::test_a_row_missing_either_plane_is_dropped_and_counted'),
    ('eda/analyze/signal.py',
     '            "in_test_window": float(((d >= TEST_MIN_S) & (d <= TEST_MAX_S)).mean())',
     '            "in_test_window": float((d >= TEST_MIN_S).mean())',
     'duration is read against the test window',
     'tests/test_eda_report.py::test_the_duration_report_reads_against_the_test_window'),
    ('eda/analyze/signal.py',
     '            "bandwidth_lost_hz": _q(g["delta"], 0.5),',
     '            "bandwidth_lost_hz": _q(g[NATIVE], 0.5) - _q(g[CHAIN], 0.5),',
     'the bandwidth loss is paired per file',
     'tests/test_eda_report.py::test_the_bandwidth_report_pairs_each_file_with_itself'),
    ('eda/analyze/signal.py',
     '    cols = {c: pd.to_numeric(signal[f"{c}_{CHAIN}"], errors="coerce")',
     '    cols = {c: pd.to_numeric(signal[f"{c}_{NATIVE}"], errors="coerce")',
     'level is read on the chain plane',
     'tests/test_eda_report.py::test_the_level_report_is_read_on_the_chain_plane'),
    ('eda/analyze/signal.py',
     '            "frac_clipping": float((g["clipping_ratio"].fillna(0) > 0).mean()),',
     '            "frac_clipping": float(g["clipping_ratio"].fillna(0).mean()),',
     'clipping counts files, not samples',
     'tests/test_eda_report.py::test_clipping_counts_files_not_samples'),
    ('eda/analyze/signal.py',
     'def signal_audit(signal: pd.DataFrame, cfg=None, *, plane: str = CHAIN,',
     'def signal_audit(signal: pd.DataFrame, cfg=None, *, plane: str = NATIVE,',
     'the signal audit runs on the chain plane',
     'tests/test_eda_report.py::test_the_signal_audit_runs_on_the_chain_plane_by_default'),
    ('eda/analyze/shortcut.py',
     '        if group_column not in sub.columns:',
     '        if False:',
     'the audit names a missing group column',
     'tests/test_eda_report.py::test_the_audit_refuses_a_group_column_the_frame_lacks'),
    ('eda/analyze/shortcut.py',
     '    if unknown:\n        raise KeyError(',
     '    if False:\n        raise KeyError(',
     'a typo\'d feature group is refused',
     'tests/test_eda_report.py::test_a_feature_spec_with_an_unknown_group_is_refused'),
    ('eda/cli.py',
     '    scope = f"_{args.partition}" if args.partition else ""',
     '    scope = ""',
     'a scoped report keeps its own filename',
     'tests/test_eda_report.py::test_a_partition_scoped_report_does_not_overwrite_the_corpus_wide_one'),
    # --- docs/EDA/09 step 1: the publisher's grouping key -------------------
    ('eda/groupkeys.py',
     '    missing = [f for f in files["file_id"] if f not in keys.index\n               or pd.isna(keys.get(f))]',
     '    missing = [f for f in files["file_id"] if False]',
     'a partial key is refused',
     'tests/test_eda_groupkeys.py::test_a_key_that_misses_a_row_raises_rather_than_writing_a_null'),
    ('eda/groupkeys.py',
     '               or pd.isna(keys.get(f))]',
     ']',
     'a null key counts as missing',
     'tests/test_eda_groupkeys.py::test_a_key_present_but_null_counts_as_missing'),
    ('eda/groupkeys.py',
     '        return pd.Series(["/".join(p[:d + 1]) if p else "" for p in parts],',
     '        return pd.Series([p[d] if p else "" for p in parts],',
     'a path key is the prefix, not the name',
     'tests/test_eda_groupkeys.py::test_a_path_key_is_the_prefix_not_the_name_at_that_depth'),
    ('eda/groupkeys.py',
     '        out.loc[rows.index, KEY_COLUMN] = (',
     '        if result.kind == PATH:\n            continue\n        out.loc[rows.index, KEY_COLUMN] = (',
     'a source with no provider still gets a path key',
     'tests/test_eda_groupkeys.py::test_a_source_with_no_provider_still_gets_a_key_from_its_path'),
    ('eda/groupkeys.py',
     '        return f"{source.name}/" + "_".join(parts[:4])',
     '        return f"{source.name}/" + "_".join(parts[:5])',
     'the room key merges its channels',
     'tests/test_eda_groupkeys.py::test_the_room_key_merges_channels_of_one_recording'),
    ('eda/groupkeys.py',
     '        return JSUT_SPEAKER if vocoder.startswith("jsut_") else LJ_SPEAKER',
     '        return f"{source.name}/{vocoder}"',
     'wavefake shares ljspeech\'s key',
     'tests/test_eda_groupkeys.py::test_wavefake_and_ljspeech_share_a_key_because_they_share_a_speaker'),
    ('eda/analyze/grouping.py',
     '        if kind != groupkeys.PATH:',
     '        if False:',
     'the publisher key beats path depth',
     'tests/test_eda_groupkeys.py::test_the_publisher_key_replaces_path_depth_even_when_it_lowers_the_count'),
    ('eda/gates.py',
     '    stated = short[kinds != "path"]',
     '    stated = short[kinds == "path"]',
     'G-EDA3 separates the two shortfalls',
     'tests/test_eda_groupkeys.py::test_the_gate_separates_a_keyed_shortfall_from_an_unlooked_at_one'),
    ('eda/driver.py',
     '    df = attach_group_keys(cfg, df)',
     '    df = df',
     'consolidate writes the key columns',
     'tests/test_eda_groupkeys.py::test_consolidate_writes_the_key_columns'),
    ('eda/groupkeys.py',
     '        subtree = "/".join(rel.parts[1:-1])',
     '        subtree = "/".join(rel.parts[0:-1])',
     'compspoof groups by parent, not by split',
     'tests/test_eda_groupkeys.py::test_compspoof_groups_by_parent_recording_not_by_split'),
    ('eda/groupkeys.py',
     '    ("TUT", re.compile(r"^(.+?)_\\d+$")),',
     '    ("TUT", re.compile(r"^(.+)$")),',
     'each compspoof subtree has its own parent rule',
     'tests/test_eda_groupkeys.py::test_each_compspoof_subtree_gets_its_publisher_s_own_parent_rule'),
    # --- docs/EDA/09 step 1: the draw ---------------------------------------
    ('eda/sample.py',
     '    for key in sorted(groups, key=lambda k: (len(groups[k]), str(k))):',
     '    for key in sorted(groups):',
     'the spread draw spends its whole budget',
     'tests/test_eda_signal.py::test_the_spread_draw_covers_every_group_and_spends_the_whole_budget'),
    # --- docs/EDA/09 step 3: the vector half --------------------------------
    ('eda/extract/vectors.py',
     '    if power.shape[1] < 2:',
     '    if False:',
     'one STFT frame fails the vectors',
     'tests/test_eda_signal.py::test_a_single_frame_file_fails_the_vectors_rather_than_emitting_nan_skew'),
    ('eda/extract/vectors.py',
     '    flat = int((log_mel.max(axis=1) - log_mel.min(axis=1) <= 0.0).sum())',
     '    flat = 0',
     'flat bands are counted, not hidden',
     'tests/test_eda_signal.py::test_a_band_that_never_moves_keeps_its_nan_and_is_counted'),
    ('eda/extract/vectors.py',
     '                                   N_MELS + 2))',
     '                                   N_MELS + 2)) * (sample_rate / 16000.0)',
     'the mel bank is the same Hz on both planes',
     'tests/test_eda_signal.py::test_the_mel_bank_is_the_same_absolute_hz_on_both_planes'),
    ('eda/extract/__init__.py',
     '        for column in self.vectors:\n            row[column] = np.full(self.width, np.nan, dtype=np.float32)',
     '        pass',
     'a vector failure has the declared width',
     'tests/test_eda_signal.py::test_a_vector_failure_has_the_declared_width_not_none'),
    ('eda/extract/__init__.py',
     '        if not vectors or unknown:',
     '        if False:',
     'a vector extractor declares its arrays',
     'tests/test_eda_signal.py::test_a_vector_extractor_must_declare_which_columns_are_arrays'),
    ('eda/driver.py',
     '    if list(keys) != list(file_ids):',
     '    if len(keys) != len(file_ids):',
     'vectors are keyed to the signal table',
     'tests/test_eda_signal.py::test_a_vector_table_that_does_not_key_like_the_signal_table_is_refused'),
    ('eda/driver.py',
     'from eda.extract import vectors as _vectors          # noqa: F401',
     '',
     'the driver registers the vector tier',
     'tests/test_eda.py::test_importing_the_driver_populates_the_signal_and_vector_registries'),
    # --- the stage, which is a config property ------------------------------
    ('eda/driver.py',
     '    path = roots[source_name] / row["path"]',
     '    path = (cfg.root if row.get("stage", "interim") == "interim" else cfg.raw) / row["path"]',
     'a raw-stage source decodes from raw',
     'tests/test_eda_signal.py::test_a_raw_stage_source_decodes_from_the_sync_tree'),
    ('eda/cli.py',
     '             "exists": cfg.source_root(s).exists(),',
     '             "exists": (cfg.root / s.root).exists(),',
     '`sources` resolves the stage',
     'tests/test_eda.py::test_sources_reports_a_raw_stage_source_as_present'),
    ('eda/driver.py',
     '                if marker.get("fingerprint") != sample.fingerprint:',
     '                if False:',
     'a redraw invalidates its old parts',
     'tests/test_eda_signal.py::test_a_redraw_invalidates_the_parts_it_no_longer_describes'),
]

py = sys.argv[1]
alive: list[str] = []
stale: list[str] = []
for path, old, new, label, test in MUTANTS:
    p = pathlib.Path(path); orig = p.read_text()
    if old not in orig:
        # 🔴 Not an assert. This harness edits files in place, and a bare
        # raise here aborts the run with whichever mutant is currently applied
        # still on disk. Measured: a `_signal_row` edit made one pattern stale,
        # the assert fired, and the run stopped after 50 of 57 with nothing
        # saying which mutants had not been tried. Report it and keep going --
        # a stale pattern is a mutant that needs rewriting, and the rest of the
        # suite is still evidence.
        stale.append(label)
        continue
    p.write_text(orig.replace(old, new, 1))
    try:
        # A bare test name means `tests/test_eda.py`; the S tier carries its own
        # file. Written this way rather than with a sixth tuple field so the 37
        # entries above did not all have to be touched to add the 38th.
        node = test if "::" in test else f"tests/test_eda.py::{test}"
        r = subprocess.run([py, "-m", "pytest", node, "-o", "addopts=", "-q"],
                           capture_output=True, text=True)
        killed = r.returncode != 0
    finally:
        p.write_text(orig)
    print(f"{'KILLED ' if killed else 'ALIVE  '} {label:40s} <- {test.rsplit('::', 1)[-1]}")
    if not killed:
        alive.append(label)
tried = len(MUTANTS) - len(stale)
print(f"\n{tried - len(alive)}/{tried} mutants killed"
      + (f"; {len(stale)} not tried" if stale else ""))
for label in stale:
    # 🔴 Reported as loudly as a survivor. A mutant whose pattern has drifted
    # is an invariant with **no** paired mutation any more -- the same state
    # the harness exists to refuse -- and a silent skip would let the count
    # keep reading green while coverage quietly shrank.
    print(f"STALE   {label:40s} <- pattern no longer in the source; rewrite it")
sys.exit(1 if alive or stale else 0)
