"""Write interim/proc/REPORT.md from metadata.csv, the draw report and the run logs.
  python scripts/proc/report_md.py        (proc-dsp venv; run report.py --fix-licence first)
"""
from __future__ import annotations
import glob, json, os, re, sys
sys.path.insert(0, os.path.dirname(__file__))
import pandas as pd
import common as C

L = C.OUT / "_logs"


def speeds() -> list[tuple[str, str, str]]:
    out = []
    for f in sorted(glob.glob(str(L / "*.log"))):
        txt = open(f, errors="replace").read()
        head = re.search(r"^\[(\S+)\] todo=\d+ .*?(device=\S+ workers=\d+)?$", txt, re.M)
        last = re.findall(r"^\[(\S+)\] files=(\d+) audio_h=([\d.]+) wall_s=(\d+) x_rt=([\d.]+)", txt, re.M)
        if last:
            tag, n, h, w, x = last[-1]
            where = head.group(2) if head and head.group(2) else "cpu, 14 workers"
            out.append((os.path.basename(f), f"{tag}: {n} files, {h} h audio in {int(w)/60:.0f} min", f"{x}x RT ({where})"))
    return out


def md_table(df: pd.DataFrame) -> str:
    cols = [df.index.name or ""] + list(df.columns) if not isinstance(df.index, pd.MultiIndex) else list(df.index.names) + list(df.columns)
    lines = ["| " + " | ".join(map(str, cols)) + " |", "|" + "---|" * len(cols)]
    for tup in df.itertuples():
        idx = tup[0] if isinstance(tup[0], tuple) else (tup[0],)
        lines.append("| " + " | ".join(map(str, list(idx) + list(tup[1:]))) + " |")
    return "\n".join(lines)


def main():
    d = pd.read_csv(C.META)
    d = d[~d.file.duplicated(keep="last")]
    kept = d.kept.astype(str).str.lower().isin(["true", "1"])
    k = d[kept]
    plan = pd.read_parquet(C.OUT / "_plan" / "draw.parquet")
    pl = plan.groupby(["family", "side"]).agg(planned=("file_id", "size"), planned_h=("duration_s", "sum"))
    t = (d.groupby(["family", "side"]).agg(written=("file", "size"))
         .join(k.groupby(["family", "side"]).agg(kept=("file", "size"), kept_h=("duration_s", "sum"))))
    t = pl.join(t, how="left").fillna(0)
    t["planned_h"] = (t.planned_h / 3600).round(2); t["kept_h"] = (t.kept_h / 3600).round(2)
    t = t.astype({"planned": int, "written": int, "kept": int})
    tl = (k.groupby(["family", "side", "tool"]).duration_s.sum() / 3600).round(2).rename("kept_h").to_frame()
    lang = (k.merge(plan[["file_id", "side", "lang"]].drop_duplicates(), left_on=["source_file_id", "side"],
                    right_on=["file_id", "side"]).groupby(["side", "lang"]).duration_s.sum() / 3600).round(2)
    drops = d[~kept].groupby(["family", "side", "drop_reason"]).size().rename("files").to_frame()
    lic = d.groupby("tool").agg(licence=("licence", "first"), version=("tool_version", "first"))
    dr = json.loads((C.OUT / "_plan" / "draw_report.json").read_text())
    tot = (k.groupby("side").duration_s.sum() / 3600).round(2).to_dict()
    sp = speeds()
    v3 = pd.read_parquet(C.ROOT / "manifests" / "strategy-v3" / "manifest.parquet",
                         columns=["file_id", "speaker_ref_id", "artifact_family"])
    kk = k.merge(v3, left_on="source_file_id", right_on="file_id").merge(
        plan[["file_id", "side", "lang", "corpus"]], left_on=["source_file_id", "side"],
        right_on=["file_id", "side"], suffixes=("", "_p"))
    shares = []
    for side, g in kk.groupby("side"):
        tt = g.duration_s.sum()
        s_ = g.groupby("speaker_ref_id").duration_s.sum() / tt
        row = [side, g.speaker_ref_id.nunique(), f"{s_.max():.1%} ({s_.idxmax()})"]
        if side == "fake":
            f_ = g.groupby("artifact_family").duration_s.sum() / tt
            fe = g[g.lang == "en"]
            row += [g.artifact_family.nunique(), f"{f_.max():.1%} ({f_.idxmax()})",
                    f"{fe[fe.corpus == 'wavefake'].duration_s.sum() / fe.duration_s.sum():.1%}"]
        else:
            row += ["-", "-", "-"]
        shares.append(row)
    shares = pd.DataFrame(shares, columns=["side", "speakers", "max speaker share", "artifact families",
                                           "max family share", "WaveFake share of en"]).set_index("side")
    md = f"""# S1 processed audio: REPORT

Track A of docs/training/09 (§2 S1). Label-preserving processing (DACON #417333 A1), applied
identically to a REAL voice subset (pool A, label stays real) and a FAKE voice subset (pool B,
label stays fake). Generated by `scripts/proc/` (not committed). Reader: `processing/extend.py::_proc`.

**Kept hours by side:** {tot} (after the WaveFake trim below)

## Per family x side (measured from metadata.csv)

{md_table(t)}

By tool:

{md_table(tl)}

Kept hours by source language (both sides must match):

{md_table(lang.rename('kept_h').to_frame())}

## Sources and the draw (`_plan/draw.parquet`, `_plan/draw_report.json`)

- strategy-v3 manifest joined with folds.parquet; **slice == train_val only** (PROBE never read),
  pools A and B, components of 3-60 s, whole files. Seed {dr['seed']}.
- Only ko and en exist on both sides of train_val (real voice is ko / en / zh; zh has no fake
  side), so the mix is **ko 50 % / en 50 %**: the brief's 15 % "rest" went to en.
- Draw: round-robin over groups, then speakers, one file per turn. Real groups = speaker
  (3 % cap); fake groups = artifact_family (no cap: the fake pool has too few families, lead
  approved 2026-09-25).
- **WaveFake trim (lead, 22:20):** WaveFake (all one LJ speaker) ≤ 25 % of the fake en side.
  MLAAD en is 8.1 h in train_val and was already fully drawn, so fake en = MLAAD + a third of
  that in WaveFake, per processing family, and real en is subsampled per processing family to the
  same hours. **Result: ~31 h per side (ko 20 h, en 10.8 h), not 40 h.** The trim is a subset of
  the first draw (`scripts/proc/trim_wavefake.py`): nothing was re-processed; the 9,440 dropped
  rows are in `metadata_excluded.csv` and their WAVs in `_excluded/` (not ingested). The original
  plan is `_plan/draw_v1.parquet`. The way back to 40 h would be ~9 h more Korean per side
  (ko-synth families would then reach ~15 % each).

Measured on the kept files:

{md_table(shares)}

- Family assignment: rotation within (side, lang, group), so every processing family sees every
  group on both sides; ~8 h per family per side, ~4 h per family per side per language.
- Per-file transform parameters are drawn from the file's `seed` column (stable in the draw seed
  and file_id), so a rerun reproduces them.

## Families, tools, parameters

| family | tool | parameters (per file, recorded in params_json) | output rate |
|---|---|---|---|
| proc-encodec | EnCodec 24 kHz (transformers `facebook/encodec_24khz`) | bandwidth from {{1.5, 3, 6, 12}} kbps | 24 kHz |
| proc-dac | Descript Audio Codec 1.0.0, 16 kHz and 44.1 kHz models | model 50/50; n_quantizers low {{2,3,4}} or high (16k {{8,12}}, 44k {{6,9}}) | 16 / 44.1 kHz |
| proc-codec-lm | XCodec2 (`HKUSTAudio/xcodec2`) and Mimi (`kyutai/mimi`, transformers), 50/50 by file seed | Mimi num_quantizers {{8,16,32}}; XCodec2 has one fixed setting (1 x 65,536 codebook, 50 Hz) | 16 kHz (XCodec2) / 24 kHz (Mimi) |
| proc-enhance | DeepFilterNet3 (`deepfilternet` 0.5.6) | atten_lim_db from {{6, 12, 18, 24, unlimited}} | 48 kHz |
| proc-dsp | Praat via parselmouth (PSOLA) and librosa (phase vocoder) | one op: pitch ±1-4 st (40 %: Praat PSOLA or librosa), formant ratio 0.85-0.95 / 1.05-1.2 (30 %: Praat Change gender, pitch kept), time-stretch 0.9-0.98 / 1.02-1.1 (30 %: Praat overlap-add or librosa) | source rate (≥16 kHz) |

Inputs are resampled with soxr (VHQ) to each model's rate. Codec outputs are trimmed to the
input length. Output is peak-limited to 0.999 only when a tool overshoots full scale (recorded as
`peak_normalised_from`).

### Licences and versions (checked 2026-09-25)

{md_table(lic)}

- EnCodec: facebookresearch/encodec is MIT (GitHub API, README "code ... MIT"). The HF card's
  licence field is empty and the README does not name a separate weight licence, so the
  **weights' licence is UNVERIFIED** (treated as MIT, the repo that distributes them).
- DAC: README "Weights are released as part of this repo under MIT license".
- DeepFilterNet: README "dual-licensed under either MIT or Apache-2.0" (GitHub reports NOASSERTION because of the dual licence).
- Mimi: HF card CC-BY-4.0. XCodec2: HF card CC-BY-NC-4.0 (NC is allowed, #417212); it loads
  facebook/w2v-bert-2.0 (MIT) as its semantic encoder.
- parselmouth GPL-3.0 and librosa ISC cover the tools, not the output audio.

## Speeds (measured, wall clock, including model load)

| log | work | speed |
|---|---|---|
""" + "\n".join(f"| {a} | {b} | {c} |" for a, b, c in sp) + f"""

CPU runs used this host outside Slurm with ≤14 worker processes, 1 torch thread each (the host
load average was 95-140 from other users, so CPU numbers are conservative). The dac-cpu files count includes rows it skipped because the GPU pass had already written them; its 2.3x is measured before the passes met. GPU runs:
Slurm job 220196 (`debug`, 1 H200, `-c 6`, 21:59-22:09 KST) ran DAC and XCodec2 as two processes
on its one allocated GPU. DAC also ran on CPU from the back of its plan as insurance while the job
queued (4,101 of its 7,406 files; the GPU did 3,249, a smoke test 56). The CPU and GPU passes met in the middle, and the dedup under
the lock kept one row per file.

## QC and drops

Same rule on both sides: kept = duration ≥ 3 s, rms ≥ -45 dBFS, finite, not all-silent.

{md_table(drops) if len(drops) else "No drops."}

- `short`: DSP time-stretch at rate > 1 pushes files near the floor under 3 s. On DAC and
  DeepFilterNet, 3.000 s sources come out 0.5-24 ms short after resampling.
- `quiet`: Zeroth / Common Voice ko sources that sit near -45 dBFS drop just below it after the
  codec or the enhancer. That is why these drops are on the real side only: those corpora are
  real. 24 real files, 0.13 % of the side.

## Output sanity (measured 2026-09-25 22:15, 20 random kept files per tool)

Waveform correlation with the resampled source: DeepFilterNet3 median 1.00, Mimi 0.92, DAC 44k
0.92, EnCodec 0.83, XCodec2 0.68 (a semantic codec, so phase is not kept), DSP 0.05 (expected: pitch
and tempo move the waveform). DAC 16 kHz reads 0.12-0.34 at lag 0 because its output is **delayed
by a constant 8 samples (0.5 ms)**. At that lag it reads 0.57 (2 quantizers) to 0.98 (12), and the
log-spectrogram error falls with quantizer count on DAC and EnCodec, as it should.

## For the integrator

- Full `extend_manifest(v3, only=("proc",), component_floor_s=2.5)` dry-run (nothing written):
  after the WaveFake trim, 27,497 rows, 61.58 h, 0 failed to open, 0 below floor, 0 duplicate
  sha256, 151 artifact families, 958 speaker atoms. By pool and language: A/en 10.81 h,
  A/ko 19.96 h, B/en 10.80 h, B/ko 20.01 h. `validate_manifest` and `check_rules` passed.
- Only `metadata.csv` is ingested; `metadata_excluded.csv` and `_excluded/` are the trimmed-off rows.

- `_proc` dry-run on this metadata passes: 0 duplicate file_ids, every source_file_id in v3, all
  probed files open. Rows keep their SOURCE's pool, language, speaker atom and (fake) artifact
  family. `source_name` = `<proc-family>/<source source_name>`.
- Resumability: rows are appended under a file lock; a WAV is committed (renamed) under the same
  lock only if its row is new, so concurrent CPU and GPU runs of one family cannot double-write.
  Every runner skips files already in metadata.csv, so rerunning a script finishes a partial run.
- Sample rates differ by family (16-48 kHz), and on the DSP family they follow the source, the same
  on both sides per source corpus. The renderer resamples to 16 kHz.
- The fake side's speaker concentration (LJ) and family concentration (ko-synth) come from the
  base pool B, not from processing; `proc-*` is balanced by construction per side and language.
- The audit's I1 check on `proc-*` (processing must not predict the label) is the integrator's.
"""
    (C.OUT / "REPORT.md").write_text(md)
    print(md)


if __name__ == "__main__":
    main()
